### ISSUE TITLE
building with android studio

### ISSUE THREAD

**Issue by elektrischermoench** [NiciDieNase/chaosflix#13]
When I build the app with android studio and start it via adb I always get the following exception:
                                                                        java.lang.RuntimeException: Unable to resume activity {de.nicidienase.chaosflix/de.nicidienase.chaosflix.activities.ConferencesActivity}: android.database.sqlite.SQLiteException: no such table: WATCHLIST_ITEM (code 1): , while compiling: SELECT * FROM WATCHLIST_ITEM

What is necessary to start the app with ads. Am I missing something?

**Comment by NiciDieNase** [comment]
The "no such table"-exception is apparently caused by SugarORM and InstantRun. (see https://stackoverflow.com/questions/33031570/android-sugar-orm-no-such-table-exception)

Disabling InstantRun fixed the issue in my test.

**Comment by elektrischermoench** [comment]
Thank you for your response. Unfortunately it does not fix the issue for me. Still getting the no-such-table exception after disabling instant run.

I was trying to debug, because I ran into an other issue and wanted to fix it :) I always getting HTTP 302 Error when I try to open a recording. I would like to open an new issue for that one. But before doing so I would like to figure out whats going on and give more feedback through debugging.

**Comment by elektrischermoench** [comment]
Ah damn it! You were right turn off instant run and make a clean install of the app does the trick for me.
Thank you. I'll try to debug my other problem and give you some feedback on that too.
