### ISSUE TITLE
Download location (SD card support)

### ISSUE THREAD

**Issue by eriktews** [NiciDieNase/chaosflix#21]
Hi

It would be great when I could select which directory is used for the downloads. My tablet has an SD card with much more space than the internal storage, so I would like to use it for the downloads.

**Comment by fpetry** [comment]
+1

I was also missing this feature when trying to save a lot of talks for the train after congress...

**Comment by eriktews** [comment]
Maybe some help how this can be implemented: First of all, the actual download seems to be triggered here:

https://github.com/NiciDieNase/chaosflix-touch/blob/55b67c0fc00cb17520d376c5d669a97bc80e7146/touch/src/main/java/de/nicidienase/chaosflix/touch/OfflineItemManager.kt#L97

However, getting the storage mountpoints on Android in a way that it works on every device is rather hard, but there might be a better solution:

https://github.com/passy/Android-DirectoryChooser

So with that, the user might be able to choose the optimal directory for the downloads.

**Comment by NiciDieNase** [comment]
Merged @eriktews pull-request
