### ISSUE TITLE
Something is messed up with keyboard based navigation

### ISSUE THREAD

**Issue by sokoow** [NiciDieNase/chaosflix#32]
Yo, I got a TV box on android 7.1 that uses irda and probably just some simple input layer that sends keys/arrows. Now, interesting thing happens on that box when I try to run chaosflix - so basically, I can move around the conference selection top navbar with left-right arrows without a problem, but I can't drop down into media selection squares when I press down - it always stays at that navbar. Anything easy to fix ? 

I'd love to watch some of talks I missed on my big screen :D Thanks a lot

**Comment by NiciDieNase** [comment]
Did you install Chaosflix from the PlayStore?
Because there is a version for TVs. I don't know how the PlayStore selects which APK to deliver to which device.
You can get both APKs here on Github under releases.
