### ISSUE TITLE
Downloads only displays some of the files actually stored.

### ISSUE THREAD

**Issue by aunwin** [NiciDieNase/chaosflix#37]
When opening the app and selecting <DOWNLOADS> from the menu, only some of the files that are stored on my phone are displayed. As far as I can see it only displays talks from the latest congress 35C3 and others (such as EH or 34c3) are not offered/displayed.
I doublechecked the files on disk and cleared the cache of the app. The issue still remains.

Chaosflix Version 0.5
Android Version 8.0.0

**Comment by NiciDieNase** [comment]
The app does not actively search for files in the given folder, it only tracks what it has downloaded itself.
Where the talks that where not listed downloaded via chaosflix?

**Comment by aunwin** [comment]
That might have been the case. Thank you for letting me know.
