### ISSUE TITLE
🚨 Use a specific user agent for media.ccc.de 🚨

### ISSUE THREAD

**Issue by manno** [NiciDieNase/chaosflix#39]
Hi,

Requests from 'okhttp' to the public JSON API of media.ccc.de make up 98% of the total traffic now and it's affecting performance.
Maybe some of those requests can be avoided,  seems odd that we output several 100gb of JSON each day. However I'm not sure where those requests are coming from.

As first countermeasure I want to rate limit the 'okhttp' user agent. If I understand correctly chaosflix currently uses that agent? Can you set an app specific agent, so we can tell the apps apart?

**Comment by NiciDieNase** [comment]
The custom useragent will be in the format "chaosflix/_app-version_ Android/_OS-Version_ (_device_)", for example:"chaosflix/0.6 Android/10 (google Pixel 2)".

It is merged to develop and will be included in the next release.
